import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import Top from '../components/Top'
import styles from '../styles/Home.module.css'
import "bootstrap/dist/css/bootstrap.min.css"; // Import bootstrap CSS


export default function About() {
return (

<>  
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
<link
href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&family=Poppins:wght@600;700&display=swap"
rel="stylesheet"
/>
<link
href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
rel="stylesheet"
/>
<link
href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"
rel="stylesheet"
/>
<link href="lib/animate/animate.min.css" rel="stylesheet" />
<link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" />

<link href="css/style.css" rel="stylesheet" />
<link href="css/ftn.css" rel="stylesheet" />

<Head>
  <title>Salong</title>
  <meta name="description" content="Generated by create next app" />
  <link rel="icon" href="/favicon.ico" />
</Head>

<Top />
  <Navbar />

<main className={styles.main}> 
{/* Feature  */}
<div className="container-xxl py-5">
<div className="container">
  <div className="row g-5">
    <div className="col-lg-6 Up">
      <h1 className="display-6 mb-5 ftn">About</h1>
      <p className="mb-4">
        About us.
        Vill du färgahåret? Du är välkommen!, just nu har 90% rabbat för
        alla våra kunder i erbjuder sveriges billigate, bästa
         <br></br>
        Vill du färgahåret? Du är välkommen!, just nu har 90% rabbat för
        alla våra kunder i erbjuder sveriges billigate, bästa
      </p>
      <div className="row g-3">
        <div className="col-sm-6">
          <div className="bg-light rounded h-100 p-3">
            <div className="bg-white d-flex flex-column justify-content-center text-center rounded h-100 py-4 px-3">
              <i className="bi bi-bookmark-check-fill ftn40 fblue" />
              <h5 className="mb-0">Easy Process</h5>
            </div>
          </div>
        </div>
        <div className="col-sm-6">
          <div className="bg-light rounded h-100 p-3">
            <div className="bg-white d-flex flex-column justify-content-center text-center rounded py-4 px-3">
              <i className="bi bi-bookmark-check-fill ftn40 fblue" />
              <h5 className="mb-0">Fast Delivery</h5>
            </div>
          </div>
        </div>
        <div className="col-sm-6">
          <div className="bg-light rounded h-100 p-3">
            <div className="bg-white d-flex flex-column justify-content-center text-center rounded py-4 px-3">
              <i className="bi bi-bookmark-check-fill ftn40 fblue" />
              <h5 className="mb-0">Policy Controlling</h5>
            </div>
          </div>
        </div>
        <div className="col-sm-6">
          <div className="bg-light rounded h-100 p-3">
            <div className="bg-white d-flex flex-column justify-content-center text-center rounded h-100 py-4 px-3">
              <i className="bi bi-bookmark-check-fill ftn40 fblue" />
              <h5 className="mb-0">Money Saving</h5>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div className="col-lg-6 Up">
      <div
        className="position-relative rounded overflow-hidden h-100"
        style={{ minHeight: 400 }}
      >
        <Image
          className="position-absolute w-100 h-100"
          src="/public/../img/feature.jpg"
          alt=""
          style={{ objectFit: "cover" }}
          layout='fill'
        />
      </div>
    </div>
  </div>
</div>
</div>
{/* //Features  */}
 

</main>


          <Footer />

<script src="https://code.jquery.com/jquery-3.4.1.min.js" async></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" async></script>
<script src="js/owlcarousel/owl.carousel.min.js" async></script>
<script src="js/script.js" async></script>
</>


)
}